name: Build and Deploy to Elastic Beanstalk

on:
  push:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Node.js Environment
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install Dependencies
      run: npm ci

    - name: Test
      run: npm test

    - name: Build
      run: npm build

    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*' . -x 'node_modules*'

    - name: Archive Application
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: deploy.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: app

    - name: unzip artifact for deployment
      run: unzip deploy.zip

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: af-south-1

    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: 'sample-nodejs'
        environment_name: 'Sample-nodejs-DEV'
        region: af-south-1
        version_label: ${{ github.sha }}
        deployment_package: deploy.zip
        use_existing_version_if_available: true
